/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desktop;

//import ucunix.Debugger;

import ucunix.ProcessId;
import ucunix.Scheduler;

import java.awt.Color;

/**
 *
 * @author ucu
 */
public class ProgramWindow extends javax.swing.JPanel {
    public interface OnCloseCallback {
        void onClose();
    }
    
    private final Scheduler scheduler;
//    private final Debugger debugger;
    private final ProcessId pid;
    private final Color backgroundColor;
    private OnCloseCallback onCloseCallback;
    
    /**
     * Creates new form ProgramWindow
     * 
     * @param process
     */
    public ProgramWindow(ProcessId pid, Scheduler scheduler) {
        this.pid = pid;
        this.scheduler = scheduler;
//        this.debugger = debugger;
        this.onCloseCallback = null;
        
        initComponents();
        
        backgroundColor = getBackground();
    }

    public void setOnCloseCallback(OnCloseCallback callback) {
        this.onCloseCallback = callback;
    }

    private void setStoppedColor() {
        setBackground(Color.YELLOW);
    }
 
    private void setPlayingColor() {
        setBackground(backgroundColor);
    }

    public ConsoleWidget getConsoleWidget() {
        return consoleWidget;
    }

    public void killProcess() {
        scheduler.killProcess(pid);
    }
    
    public void update() {
        var process = scheduler.getProcess(pid);
        if (process != null) {
            pidLabel.setText(pid.toString());
            programPathLabel.setText(process.getName());
        } else {
            onProcessFinished();
        }
    }
    
    private void onProcessFinished() {
        setBackground(new Color(204, 204, 255));
        debuggerButton.setEnabled(false);
        sourceCodeButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consoleWidget = new desktop.ConsoleWidget();
        closeButton = new javax.swing.JButton();
        debuggerButton = new javax.swing.JButton();
        sourceCodeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        programPathLabel = new javax.swing.JLabel();
        pidTextLabel = new javax.swing.JLabel();
        pidLabel = new javax.swing.JLabel();

        consoleWidget.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        closeButton.setText("Cerrar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        debuggerButton.setText("Debugger");
        debuggerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debuggerButtonActionPerformed(evt);
            }
        });

        sourceCodeButton.setText("Código Fuente");
        sourceCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSourceCodeButtonClicked(evt);
            }
        });

        programPathLabel.setText("path/to/program.uculang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(programPathLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programPathLabel)
        );

        pidTextLabel.setText("PID:");

        pidLabel.setText("1234");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pidTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pidLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sourceCodeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debuggerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(consoleWidget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debuggerButton)
                    .addComponent(closeButton)
                    .addComponent(sourceCodeButton)
                    .addComponent(pidTextLabel)
                    .addComponent(pidLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consoleWidget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if (onCloseCallback != null) {
            onCloseCallback.onClose();
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void debuggerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debuggerButtonActionPerformed
//        var frame = new DebuggerFramef(pid, debugger);
//        frame.setVisible(true);
    }//GEN-LAST:event_debuggerButtonActionPerformed

    private void onSourceCodeButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSourceCodeButtonClicked
        var process = scheduler.getProcess(pid);
        if (process != null) {
            String sourceCode = process.getInterpreter()
                                    .getContext()
                                    .getProgram()
                                    .getSourceCode();

            var frame = new SourceCodeFrame(sourceCode);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_onSourceCodeButtonClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private desktop.ConsoleWidget consoleWidget;
    private javax.swing.JButton debuggerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JLabel pidTextLabel;
    private javax.swing.JLabel programPathLabel;
    private javax.swing.JButton sourceCodeButton;
    // End of variables declaration//GEN-END:variables
}
