/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desktop;

import java.util.stream.Collectors;

import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

import ucunix.sdk.Semaphore;
import ucunix.sdk.SharedVariables;

import java.awt.event.ActionEvent;

/**
 *
 * @author ucu
 */
public class SemaphoresViewerFrame extends javax.swing.JFrame {

    private final Timer updateTimer;

    /**
     * Creates new form SemaphoresViewerFrame
     */
    public SemaphoresViewerFrame() {
        initComponents();

        update();
        updateTimer = new Timer(50, (ActionEvent e) -> {
            update();
        });
        updateTimer.start();
    }

    private void update() {
        var sem = SharedVariables.getAll().values()
            .stream()
            .filter(x -> x.value instanceof Semaphore)
            .map(x -> (Semaphore) x.value)
            .toList();

        var model = new DefaultTableModel();
        model.setDataVector(
            sem.stream()
                .map(x -> new String[] { x.getName(), String.valueOf(x.getCapacity()), x.getBlockedPids().toString() })
                .collect(Collectors.toList())
                .toArray(new String[0][0]), 
            new String[] { "Semáforos", "Capacidad", "Bloqueados" }
        );
        semaphoresTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        semaphoresTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        semaphoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        semaphoresTable.setShowGrid(true);
        jScrollPane1.setViewportView(semaphoresTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        updateTimer.stop();
    }//GEN-LAST:event_onWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable semaphoresTable;
    // End of variables declaration//GEN-END:variables
}
